tag 1			a 
  JUMPDEST 			a 
  POP 			constructor(uint daysCompletio...
  PUSH 40			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  PUSHSIZE 			constructor(uint daysCompletio...
  CODESIZE 			constructor(uint daysCompletio...
  SUB 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  PUSHSIZE 			constructor(uint daysCompletio...
  DUP4 			constructor(uint daysCompletio...
  CODECOPY 			constructor(uint daysCompletio...
  DUP2 			constructor(uint daysCompletio...
  DUP2 			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  PUSH 40			constructor(uint daysCompletio...
  MSTORE 			constructor(uint daysCompletio...
  PUSH 60			ty
  DUP2 			oli
  LT 			a solidity 
  ISZERO 			ag
  PUSH [tag] 2			ag
  JUMPI 			ag
  PUSH 0			.
  DUP1 			0
  REVERT 			.4.22 <0.6.0
tag 2			ag
  JUMPDEST 			ag
  DUP2 			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  PUSH 20			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  SWAP3 			constructor(uint daysCompletio...
  SWAP2 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  PUSH 20			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  SWAP3 			constructor(uint daysCompletio...
  SWAP2 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  PUSH 40			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  SWAP4 			constructor(uint daysCompletio...
  SWAP3 			constructor(uint daysCompletio...
  SWAP2 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  DUP5 			constructor(uint daysCompletio...
  PUSH 100000000			.4.22 <0.6.
  DUP3 			y >
  GT 			dity >=0.4.22 <0.6.0
  ISZERO 			ol
  PUSH [tag] 3			ol
  JUMPI 			ol
  PUSH 0			 
  DUP1 			a
  REVERT 			\r\ncontract c
tag 3			ol
  JUMPDEST 			ol
  DUP4 			/Funder Str
  DUP3 			   
  ADD 			  \r\n    //Funder Stru
  SWAP2 			ng{\r\n    \r\n    //Funder St...
  POP 			ng{\r\n    \r\n    //Funder St...
  PUSH 20			nd;\r
  DUP3 			nt 
  ADD 			  uint fund;\r\n
  DUP6 			    \r\n   
  DUP2 			position;\r\n    }
  GT 			nt position;\r\n    }\r\n    \...
  ISZERO 			 u
  PUSH [tag] 4			 u
  JUMPI 			 u
  PUSH 0			 
  DUP1 			s
  REVERT 			ariables\r\n  
tag 4			 u
  JUMPDEST 			 u
  DUP3 			   
  MLOAD 			oal;\r\n    
  DUP7 			g(address
  PUSH 20			ma
  DUP3 			Funders;\r\n  
  MUL 			 allFunders;\r\n    map
  DUP4 			 address payable
  ADD 			\n    address payable[] allFun...
  GT 			t;\r\n    address payable[] al...
  PUSH 100000000			  address[]
  DUP3 			ess owner;\r\n
  GT 			ddress owner;\r\n    address[]...
  OR 			ues;\r\n    address owner;\r\n...
  ISZERO 			va
  PUSH [tag] 5			va
  JUMPI 			va
  PUSH 0			a
  DUP1 			T
  REVERT 			addressToVal
tag 5			va
  JUMPDEST 			va
  DUP1 			 => int) ind
  DUP4 			(ui
  MSTORE 			mapping(uint => int) inde
  PUSH 20			ruct
  DUP4 			Con
  ADD 			  //Constructo
  SWAP3 			   \r\n    //Constructo
  POP 			   \r\n    //Constructo
  POP 			pragma solidity >=0.4.22 <0.6....
  POP 			pragma solidity >=0.4.22 <0.6....
  SWAP1 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  MLOAD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  PUSH 20			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  PUSH 20			constructor(uint daysCompletio...
  MUL 			constructor(uint daysCompletio...
  DUP1 			constructor(uint daysCompletio...
  DUP4 			constructor(uint daysCompletio...
  DUP4 			constructor(uint daysCompletio...
  PUSH 0			2
tag 6			olidity >=0.4.22 <0.6.0;\r\n\r...
  JUMPDEST 			olidity >=0.4.22 <0.6.0;\r\n\r...
  DUP4 			\n\r\n
  DUP2 			0
  LT 			.6.0;\r\n\r\nc
  ISZERO 			olidity >=0.4.22 <0.6.0;\r\n\r...
  PUSH [tag] 8			olidity >=0.4.22 <0.6.0;\r\n\r...
  JUMPI 			olidity >=0.4.22 <0.6.0;\r\n\r...
  DUP1 			u
  DUP3 			uct
  ADD 			 struct fun
  MLOAD 			t\r\n    struct fund
  DUP2 			t
  DUP5 			der
  ADD 			/Funder Str
  MSTORE 			\r\n    //Funder Struct\r\n   ...
  PUSH 20			nd
  DUP2 			d
  ADD 			crowdfundi
  SWAP1 			ract crowdfundi
  POP 			ract crowdfundi
  PUSH [tag] 6			olidity >=0.4.22 <0.6.0;\r\n\r...
  JUMP 			olidity >=0.4.22 <0.6.0;\r\n\r...
tag 8			olidity >=0.4.22 <0.6.0;\r\n\r...
  JUMPDEST 			olidity >=0.4.22 <0.6.0;\r\n\r...
  POP 			ity >=0.4.22 <
  POP 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  SWAP1 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  ADD 			constructor(uint daysCompletio...
  PUSH 40			constructor(uint daysCompletio...
  MSTORE 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  POP 			constructor(uint daysCompletio...
  PUSH 0			0
  DUP3 			goalinWei
  EQ 			goalinWei != 0
  ISZERO 			goalinWei != 0
  PUSH [tag] 11			require(goalinWei != 0,"Need g...
  JUMPI 			require(goalinWei != 0,"Need g...
  PUSH 40			require(goalinWei != 0,"Need g...
  MLOAD 			require(goalinWei != 0,"Need g...
  PUSH 8C379A000000000000000000000000000000000000000000000000000000000			require(goalinWei != 0,"Need g...
  DUP2 			require(goalinWei != 0,"Need g...
  MSTORE 			require(goalinWei != 0,"Need g...
  PUSH 4			require(goalinWei != 0,"Need g...
  ADD 			require(goalinWei != 0,"Need g...
  DUP1 			require(goalinWei != 0,"Need g...
  DUP1 			require(goalinWei != 0,"Need g...
  PUSH 20			require(goalinWei != 0,"Need g...
  ADD 			require(goalinWei != 0,"Need g...
  DUP3 			require(goalinWei != 0,"Need g...
  DUP2 			require(goalinWei != 0,"Need g...
  SUB 			require(goalinWei != 0,"Need g...
  DUP3 			require(goalinWei != 0,"Need g...
  MSTORE 			require(goalinWei != 0,"Need g...
  PUSH 1E			require(goalinWei != 0,"Need g...
  DUP2 			require(goalinWei != 0,"Need g...
  MSTORE 			require(goalinWei != 0,"Need g...
  PUSH 20			require(goalinWei != 0,"Need g...
  ADD 			require(goalinWei != 0,"Need g...
  DUP1 			require(goalinWei != 0,"Need g...
  PUSH 4E65656420676F616C20746F206265206D6F7265207468616E207A65726F0000			require(goalinWei != 0,"Need g...
  DUP2 			require(goalinWei != 0,"Need g...
  MSTORE 			require(goalinWei != 0,"Need g...
  POP 			require(goalinWei != 0,"Need g...
  PUSH 20			require(goalinWei != 0,"Need g...
  ADD 			require(goalinWei != 0,"Need g...
  SWAP2 			require(goalinWei != 0,"Need g...
  POP 			require(goalinWei != 0,"Need g...
  POP 			require(goalinWei != 0,"Need g...
  PUSH 40			require(goalinWei != 0,"Need g...
  MLOAD 			require(goalinWei != 0,"Need g...
  DUP1 			require(goalinWei != 0,"Need g...
  SWAP2 			require(goalinWei != 0,"Need g...
  SUB 			require(goalinWei != 0,"Need g...
  SWAP1 			require(goalinWei != 0,"Need g...
  REVERT 			require(goalinWei != 0,"Need g...
tag 11			require(goalinWei != 0,"Need g...
  JUMPDEST 			require(goalinWei != 0,"Need g...
  PUSH 0			0
  DUP2 			insertValues
  MLOAD 			insertValues.length
  EQ 			insertValues.length != 0
  ISZERO 			insertValues.length != 0
  PUSH [tag] 12			require(insertValues.length !=...
  JUMPI 			require(insertValues.length !=...
  PUSH 40			require(insertValues.length !=...
  MLOAD 			require(insertValues.length !=...
  PUSH 8C379A000000000000000000000000000000000000000000000000000000000			require(insertValues.length !=...
  DUP2 			require(insertValues.length !=...
  MSTORE 			require(insertValues.length !=...
  PUSH 4			require(insertValues.length !=...
  ADD 			require(insertValues.length !=...
  DUP1 			require(insertValues.length !=...
  DUP1 			require(insertValues.length !=...
  PUSH 20			require(insertValues.length !=...
  ADD 			require(insertValues.length !=...
  DUP3 			require(insertValues.length !=...
  DUP2 			require(insertValues.length !=...
  SUB 			require(insertValues.length !=...
  DUP3 			require(insertValues.length !=...
  MSTORE 			require(insertValues.length !=...
  PUSH B			require(insertValues.length !=...
  DUP2 			require(insertValues.length !=...
  MSTORE 			require(insertValues.length !=...
  PUSH 20			require(insertValues.length !=...
  ADD 			require(insertValues.length !=...
  DUP1 			require(insertValues.length !=...
  PUSH 4E6565642076616C756573000000000000000000000000000000000000000000			require(insertValues.length !=...
  DUP2 			require(insertValues.length !=...
  MSTORE 			require(insertValues.length !=...
  POP 			require(insertValues.length !=...
  PUSH 20			require(insertValues.length !=...
  ADD 			require(insertValues.length !=...
  SWAP2 			require(insertValues.length !=...
  POP 			require(insertValues.length !=...
  POP 			require(insertValues.length !=...
  PUSH 40			require(insertValues.length !=...
  MLOAD 			require(insertValues.length !=...
  DUP1 			require(insertValues.length !=...
  SWAP2 			require(insertValues.length !=...
  SUB 			require(insertValues.length !=...
  SWAP1 			require(insertValues.length !=...
  REVERT 			require(insertValues.length !=...
tag 12			require(insertValues.length !=...
  JUMPDEST 			require(insertValues.length !=...
  CALLER 			msg.sender
  PUSH 3			owner
  PUSH 0			owner
  PUSH 100			owner = msg.sender
  EXP 			owner = msg.sender
  DUP2 			owner = msg.sender
  SLOAD 			owner = msg.sender
  DUP2 			owner = msg.sender
  PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = msg.sender
  MUL 			owner = msg.sender
  NOT 			owner = msg.sender
  AND 			owner = msg.sender
  SWAP1 			owner = msg.sender
  DUP4 			owner = msg.sender
  PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = msg.sender
  AND 			owner = msg.sender
  MUL 			owner = msg.sender
  OR 			owner = msg.sender
  SWAP1 			owner = msg.sender
  SSTORE 			owner = msg.sender
  POP 			owner = msg.sender
  DUP2 			goalinWei
  PUSH 1			goal
  DUP2 			goal = goalinWei
  SWAP1 			goal = goalinWei
  SSTORE 			goal = goalinWei
  POP 			goal = goalinWei
  DUP3 			daysCompletion
  TIMESTAMP 			now
  ADD 			now + (/*24 * 60 * 60 */ daysC...
  PUSH 0			finishTime
  DUP2 			finishTime = now + (/*24 * 60 ...
  SWAP1 			finishTime = now + (/*24 * 60 ...
  SSTORE 			finishTime = now + (/*24 * 60 ...
  POP 			finishTime = now + (/*24 * 60 ...
  PUSH 0			uint i
  DUP1 			0
  SWAP1 			uint i = 0
  POP 			uint i = 0