PUSH [tag] 104			if(int(indexpos) < int(usersLe...
      JUMP 			if(int(indexpos) < int(usersLe...
    tag 96			if(int(indexpos) < int(usersLe...
      JUMPDEST 			if(int(indexpos) < int(usersLe...
      DUP1 			semirandom
      DUP4 			indexpos
      EQ 			int(indexpos) == semirandom
      ISZERO 			if(int(indexpos) == semirandom...
      PUSH [tag] 105			if(int(indexpos) == semirandom...
      JUMPI 			if(int(indexpos) == semirandom...