tag 83			while (trueLength > 0){\r\n   ...
      JUMPDEST 			while (trueLength > 0){\r\n   ...
      PUSH 0			0
      DUP3 			trueLength
      GT 			trueLength > 0
      ISZERO 			while (trueLength > 0){\r\n   ...
      PUSH [tag] 84			while (trueLength > 0){\r\n   ...
      JUMPI 			while (trueLength > 0){\r\n   ...
      PUSH 0			0
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter] != address(0)
      AND 			allFunders[iter] != address(0)
      PUSH 5			allFunders
      DUP3 			iter
      DUP2 			allFunders[iter]
      SLOAD 			allFunders[iter]
      DUP2 			allFunders[iter]
      LT 			allFunders[iter]
      PUSH [tag] 85			allFunders[iter]
      JUMPI 			allFunders[iter]
      INVALID 			allFunders[iter]
    tag 85			allFunders[iter]
      JUMPDEST 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 0			allFunders[iter]
      MSTORE 			allFunders[iter]
      PUSH 20			allFunders[iter]
      PUSH 0			allFunders[iter]
      KECCAK256 			allFunders[iter]
      ADD 			allFunders[iter]
      PUSH 0			allFunders[iter]
      SWAP1 			allFunders[iter]
      SLOAD 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 100			allFunders[iter]
      EXP 			allFunders[iter]
      SWAP1 			allFunders[iter]
      DIV 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter]
      AND 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter] != address(0)
      AND 			allFunders[iter] != address(0)
      EQ 			allFunders[iter] != address(0)
      PUSH [tag] 87			if(allFunders[iter] != address...
      JUMPI 			if(allFunders[iter] != address...
      PUSH 5			allFunders
      DUP2 			iter
      DUP2 			allFunders[iter]
      SLOAD 			allFunders[iter]
      DUP2 			allFunders[iter]
      LT 			allFunders[iter]
      PUSH [tag] 88			allFunders[iter]
      JUMPI 			allFunders[iter]
      INVALID 			allFunders[iter]
    tag 88			allFunders[iter]
      JUMPDEST 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 0			allFunders[iter]
      MSTORE 			allFunders[iter]
      PUSH 20			allFunders[iter]
      PUSH 0			allFunders[iter]
      KECCAK256 			allFunders[iter]
      ADD 			allFunders[iter]
      PUSH 0			allFunders[iter]
      SWAP1 			allFunders[iter]
      SLOAD 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 100			allFunders[iter]
      EXP 			allFunders[iter]
      SWAP1 			allFunders[iter]
      DIV 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter]
      AND 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter].transfer
      AND 			allFunders[iter].transfer
      PUSH 8FC			allFunders[iter].transfer(addr...
      DUP5 			price
      PUSH 6			addressToValue
      PUSH 0			addressToValue[allFunders[iter...
      PUSH 5			allFunders
      DUP7 			iter
      DUP2 			allFunders[iter]
      SLOAD 			allFunders[iter]
      DUP2 			allFunders[iter]
      LT 			allFunders[iter]
      PUSH [tag] 90			allFunders[iter]
      JUMPI 			allFunders[iter]
      INVALID 			allFunders[iter]
    tag 90			allFunders[iter]
      JUMPDEST 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 0			allFunders[iter]
      MSTORE 			allFunders[iter]
      PUSH 20			allFunders[iter]
      PUSH 0			allFunders[iter]
      KECCAK256 			allFunders[iter]
      ADD 			allFunders[iter]
      PUSH 0			allFunders[iter]
      SWAP1 			allFunders[iter]
      SLOAD 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 100			allFunders[iter]
      EXP 			allFunders[iter]
      SWAP1 			allFunders[iter]
      DIV 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter]
      AND 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			addressToValue[allFunders[iter...
      AND 			addressToValue[allFunders[iter...
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			addressToValue[allFunders[iter...
      AND 			addressToValue[allFunders[iter...
      DUP2 			addressToValue[allFunders[iter...
      MSTORE 			addressToValue[allFunders[iter...
      PUSH 20			addressToValue[allFunders[iter...
      ADD 			addressToValue[allFunders[iter...
      SWAP1 			addressToValue[allFunders[iter...
      DUP2 			addressToValue[allFunders[iter...
      MSTORE 			addressToValue[allFunders[iter...
      PUSH 20			addressToValue[allFunders[iter...
      ADD 			addressToValue[allFunders[iter...
      PUSH 0			addressToValue[allFunders[iter...
      KECCAK256 			addressToValue[allFunders[iter...
      PUSH 0			addressToValue[allFunders[iter...
      ADD 			addressToValue[allFunders[iter...
      SLOAD 			addressToValue[allFunders[iter...
      SUB 			addressToValue[allFunders[iter...
      SWAP1 			allFunders[iter].transfer(addr...
      DUP2 			allFunders[iter].transfer(addr...
      ISZERO 			allFunders[iter].transfer(addr...
      MUL 			allFunders[iter].transfer(addr...
      SWAP1 			allFunders[iter].transfer(addr...
      PUSH 40			allFunders[iter].transfer(addr...
      MLOAD 			allFunders[iter].transfer(addr...
      PUSH 0			allFunders[iter].transfer(addr...
      PUSH 40			allFunders[iter].transfer(addr...
      MLOAD 			allFunders[iter].transfer(addr...
      DUP1 			allFunders[iter].transfer(addr...
      DUP4 			allFunders[iter].transfer(addr...
      SUB 			allFunders[iter].transfer(addr...
      DUP2 			allFunders[iter].transfer(addr...
      DUP6 			allFunders[iter].transfer(addr...
      DUP9 			allFunders[iter].transfer(addr...
      DUP9 			allFunders[iter].transfer(addr...
      CALL 			allFunders[iter].transfer(addr...
      SWAP4 			allFunders[iter].transfer(addr...
      POP 			allFunders[iter].transfer(addr...
      POP 			allFunders[iter].transfer(addr...
      POP 			allFunders[iter].transfer(addr...
      POP 			allFunders[iter].transfer(addr...
      ISZERO 			allFunders[iter].transfer(addr...
      DUP1 			olidity >
      ISZERO 			a 
      PUSH [tag] 92			a 
      JUMPI 			a 
      RETURNDATASIZE 			crowdfunding{\r\n 
      PUSH 0			c
      DUP1 			t
      RETURNDATACOPY 			 <0.6.0;\r\n\r\ncontract crowd...
      RETURNDATASIZE 			r Struct\r\n    st
      PUSH 0			n
      REVERT 			   //Funder Struct\r\n    str
    tag 92			a 
      JUMPDEST 			a 
      POP 			allFunders[iter].transfer(addr...
      PUSH 4			funderList
      PUSH 5			allFunders
      DUP3 			iter
      DUP2 			allFunders[iter]
      SLOAD 			allFunders[iter]
      DUP2 			allFunders[iter]
      LT 			allFunders[iter]
      PUSH [tag] 93			allFunders[iter]
      JUMPI 			allFunders[iter]
      INVALID 			allFunders[iter]
    tag 93			allFunders[iter]
      JUMPDEST 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 0			allFunders[iter]
      MSTORE 			allFunders[iter]
      PUSH 20			allFunders[iter]
      PUSH 0			allFunders[iter]
      KECCAK256 			allFunders[iter]
      ADD 			allFunders[iter]
      PUSH 0			allFunders[iter]
      SWAP1 			allFunders[iter]
      SLOAD 			allFunders[iter]
      SWAP1 			allFunders[iter]
      PUSH 100			allFunders[iter]
      EXP 			allFunders[iter]
      SWAP1 			allFunders[iter]
      DIV 			allFunders[iter]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			allFunders[iter]
      AND 			allFunders[iter]
      SWAP1 			funderList.push(allFunders[ite...
      DUP1 			funderList.push(allFunders[ite...
      PUSH 1			t
      DUP2 			\n\r\n
      SLOAD 			.6.0;\r\n\r\nc
      ADD 			2 <0.6.0;\r\n\r\ncontr
      DUP1 			{\r\n    \r\n 
      DUP3 			ndi
      SSTORE 			crowdfunding{\r\n    \r\n  
      DUP1 			Struct\r\n  
      SWAP2 			Funder Struct\r\n  
      POP 			Funder Struct\r\n  
      POP 			pragma solidity >=0.4.22 <0.6....
      SWAP1 			funderList.push(allFunders[ite...
      PUSH 1			funderList.push(allFunders[ite...
      DUP3 			funderList.push(allFunders[ite...
      SUB 			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      PUSH 0			funderList.push(allFunders[ite...
      MSTORE 			funderList.push(allFunders[ite...
      PUSH 20			funderList.push(allFunders[ite...
      PUSH 0			funderList.push(allFunders[ite...
      KECCAK256 			funderList.push(allFunders[ite...
      ADD 			funderList.push(allFunders[ite...
      PUSH 0			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      SWAP2 			funderList.push(allFunders[ite...
      SWAP3 			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      SWAP2 			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      SWAP2 			funderList.push(allFunders[ite...
      PUSH 100			funderList.push(allFunders[ite...
      EXP 			funderList.push(allFunders[ite...
      DUP2 			funderList.push(allFunders[ite...
      SLOAD 			funderList.push(allFunders[ite...
      DUP2 			funderList.push(allFunders[ite...
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			funderList.push(allFunders[ite...
      MUL 			funderList.push(allFunders[ite...
      NOT 			funderList.push(allFunders[ite...
      AND 			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      DUP4 			funderList.push(allFunders[ite...
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			funderList.push(allFunders[ite...
      AND 			funderList.push(allFunders[ite...
      MUL 			funderList.push(allFunders[ite...
      OR 			funderList.push(allFunders[ite...
      SWAP1 			funderList.push(allFunders[ite...
      SSTORE 			funderList.push(allFunders[ite...
      POP 			funderList.push(allFunders[ite...
      POP 			funderList.push(allFunders[ite...
      DUP2 			trueLength--
      DUP1 			trueLength--
      PUSH 1			trueLength--
      SWAP1 			trueLength--
      SUB 			trueLength--
      SWAP3 			trueLength--
      POP 			trueLength--
      POP 			trueLength--
    tag 87			if(allFunders[iter] != address...
      JUMPDEST 			if(allFunders[iter] != address...
      DUP1 			iter++
      DUP1 			iter++
      PUSH 1			iter++
      ADD 			iter++
      SWAP2 			iter++
      POP 			iter++
      POP 			iter++
      PUSH [tag] 83			while (trueLength > 0){\r\n   ...
      JUMP 			while (trueLength > 0){\r\n   ...