CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			msg.sender.transfer
      AND 			msg.sender.transfer
      PUSH 8FC			msg.sender.transfer(msg.value)
      CALLVALUE 			msg.value
      SWAP1 			msg.sender.transfer(msg.value)
      DUP2 			msg.sender.transfer(msg.value)
      ISZERO 			msg.sender.transfer(msg.value)
      MUL 			msg.sender.transfer(msg.value)
      SWAP1 			msg.sender.transfer(msg.value)
      PUSH 40			msg.sender.transfer(msg.value)
      MLOAD 			msg.sender.transfer(msg.value)
      PUSH 0			msg.sender.transfer(msg.value)
      PUSH 40			msg.sender.transfer(msg.value)
      MLOAD 			msg.sender.transfer(msg.value)
      DUP1 			msg.sender.transfer(msg.value)
      DUP4 			msg.sender.transfer(msg.value)
      SUB 			msg.sender.transfer(msg.value)
      DUP2 			msg.sender.transfer(msg.value)
      DUP6 			msg.sender.transfer(msg.value)
      DUP9 			msg.sender.transfer(msg.value)
      DUP9 			msg.sender.transfer(msg.value)
      CALL 			msg.sender.transfer(msg.value)
      SWAP4 			msg.sender.transfer(msg.value)
      POP 			msg.sender.transfer(msg.value)
      POP 			msg.sender.transfer(msg.value)
      POP 			msg.sender.transfer(msg.value)
      POP 			msg.sender.transfer(msg.value)
      ISZERO 			msg.sender.transfer(msg.value)